#!/usr/bin/env bash
# dispatcher_single.sh — single-GPU task dispatcher
# Generated by /GPU-task-runner. Edit the CONFIG block, then: bash dispatcher_single.sh

set -euo pipefail

# ── CONFIG (filled by /GPU-task-runner) ──────────────────────────────────────
TASKS=()                  # e.g. ("item0" "item1" "item2")
CMD_TMPL=""               # e.g. "python eval.py --input {item}"
MIN_CONCURRENCY=1         # minimum number of concurrent tasks to maintain
PER_TASK_VRAM=0           # MiB required per task (0 = unknown, skip OOM check)
UTIL_THRESHOLD=80         # % — GPUs at or above this util are skipped in pass 1
ENV_ACTIVATE=""           # e.g. "source activate myenv" or "source /path/to/venv/bin/activate"
# ─────────────────────────────────────────────────────────────────────────────

LOG_DIR="logs/$(date +%Y-%m-%d_%H-%M-%S)"
mkdir -p "$LOG_DIR"

# task queue implemented as an array + head pointer
_QUEUE=("${TASKS[@]}")
_HEAD=0
_RUNNING=0

_queue_empty() { (( _HEAD >= ${#_QUEUE[@]} )); }
_queue_pop()   { echo "${_QUEUE[$_HEAD]}"; (( _HEAD++ )); }

# launch one task on a given GPU index
_launch() {
    local gpu=$1 item=$2
    local safe_id="${item//\//_}"
    local log="$LOG_DIR/${safe_id}.log"
    local cmd="${CMD_TMPL//\{item\}/$item}"
    echo "[dispatch] GPU $gpu  ←  $item"
    CUDA_VISIBLE_DEVICES=$gpu bash -c "$cmd" >"$log" 2>&1 &
    (( _RUNNING++ )) || true
}

# query GPU state: emit lines of "index util free_mib"
_query_gpus() {
    nvidia-smi --query-gpu=index,utilization.gpu,memory.free \
               --format=csv,noheader,nounits 2>/dev/null \
    | awk -F',' '{printf "%s %s %s\n", $1, $2, $3}'
}

# sort GPU lines by util% ascending; print "index util free_mib"
_sort_by_util() {
    sort -k2 -n
}

# core dispatch function — called once at startup and after every task exit
scan_and_dispatch() {
    _queue_empty && return

    # snapshot current GPU state
    local gpu_data
    gpu_data=$(_query_gpus | _sort_by_util)

    # pass 1: util + VRAM constraint
    local dispatched_this_pass=0
    while IFS=' ' read -r idx util free_mib; do
        _queue_empty && break
        # hard OOM check
        if (( PER_TASK_VRAM > 0 )); then
            local usable=$(( free_mib * 85 / 100 ))
            (( usable < PER_TASK_VRAM )) && continue
        fi
        # soft util check
        (( util >= UTIL_THRESHOLD )) && continue
        _launch "$idx" "$(_queue_pop)"
        (( dispatched_this_pass++ )) || true
    done <<< "$gpu_data"

    # pass 2: VRAM only — fill up to MIN_CONCURRENCY if still below
    if (( _RUNNING < MIN_CONCURRENCY )) && ! _queue_empty; then
        while IFS=' ' read -r idx util free_mib; do
            _queue_empty && break
            (( _RUNNING >= MIN_CONCURRENCY )) && break
            if (( PER_TASK_VRAM > 0 )); then
                local usable=$(( free_mib * 85 / 100 ))
                (( usable < PER_TASK_VRAM )) && continue
            fi
            _launch "$idx" "$(_queue_pop)"
        done <<< "$gpu_data"
    fi
}

# ── main ─────────────────────────────────────────────────────────────────────

if ! command -v nvidia-smi &>/dev/null; then
    echo "ERROR: nvidia-smi not found. Check GPU drivers." >&2
    exit 1
fi

[[ -n "$ENV_ACTIVATE" ]] && eval "$ENV_ACTIVATE"

echo "Starting dispatcher | tasks: ${#_QUEUE[@]} | min_concurrency: $MIN_CONCURRENCY"
echo "Logs → $LOG_DIR"

scan_and_dispatch

while (( _RUNNING > 0 )) || ! _queue_empty; do
    # wait for any child to exit
    if wait -n 2>/dev/null; then
        (( _RUNNING-- )) || true
    else
        # bash < 4.3 fallback: wait for all, reset counter
        wait
        _RUNNING=0
    fi
    scan_and_dispatch
done

echo "All tasks done. Logs: $LOG_DIR"
