#!/usr/bin/env bash
# dispatcher_multi.sh — multi-GPU task dispatcher (one task spans k consecutive GPUs)
# Generated by /GPU-task-runner. Edit the CONFIG block, then: bash dispatcher_multi.sh

set -euo pipefail

# ── CONFIG (filled by /GPU-task-runner) ──────────────────────────────────────
TASKS=()                  # e.g. ("item0" "item1" "item2")
CMD_TMPL=""               # e.g. "torchrun --nproc_per_node {ngpu} train.py --data {item}"
                          # placeholders: {item} = task arg, {ngpu} = GPUS_PER_TASK,
                          #               {gpu_list} = "0,1,2,3" (set via CUDA_VISIBLE_DEVICES)
GPUS_PER_TASK=2           # number of consecutive GPUs required per task
MIN_CONCURRENCY=1         # minimum number of concurrent tasks to maintain
PER_TASK_VRAM=0           # MiB required per GPU per task (0 = skip OOM check)
UTIL_THRESHOLD=80         # % — GPU groups where any card exceeds this are skipped in pass 1
ENV_ACTIVATE=""           # e.g. "source activate myenv"
# ─────────────────────────────────────────────────────────────────────────────

LOG_DIR="logs/$(date +%Y-%m-%d_%H-%M-%S)"
mkdir -p "$LOG_DIR"

_QUEUE=("${TASKS[@]}")
_HEAD=0
_RUNNING=0

_queue_empty() { (( _HEAD >= ${#_QUEUE[@]} )); }
_queue_pop()   { echo "${_QUEUE[$_HEAD]}"; (( _HEAD++ )); }

# launch one task on k consecutive GPUs starting at gpu index $1
_launch() {
    local start_idx=$1 item=$2
    local gpu_list=""
    for (( i=0; i<GPUS_PER_TASK; i++ )); do
        gpu_list+="$(( start_idx + i ))"
        (( i < GPUS_PER_TASK - 1 )) && gpu_list+=","
    done
    local safe_id="${item//\//_}"
    local log="$LOG_DIR/${safe_id}.log"
    local cmd="${CMD_TMPL//\{item\}/$item}"
    cmd="${cmd//\{ngpu\}/$GPUS_PER_TASK}"
    cmd="${cmd//\{gpu_list\}/$gpu_list}"
    echo "[dispatch] GPUs $gpu_list  ←  $item"
    CUDA_VISIBLE_DEVICES=$gpu_list bash -c "$cmd" >"$log" 2>&1 &
    (( _RUNNING++ )) || true
}

# query GPU state: emit lines of "index util free_mib"
_query_gpus() {
    nvidia-smi --query-gpu=index,utilization.gpu,memory.free \
               --format=csv,noheader,nounits 2>/dev/null \
    | awk -F',' '{printf "%s %s %s\n", $1, $2, $3}'
}

# check if k consecutive GPUs starting at position $1 in the sorted index array
# all satisfy constraints; sets _GROUP_START_IDX to the real GPU index on success
_find_group() {
    local pass=$1   # 1 = util+vram, 2 = vram only
    shift
    local -a indices=("$@")
    local n=${#indices[@]}
    # iterate over possible start positions
    for (( s=0; s <= n - GPUS_PER_TASK; s++ )); do
        local ok=1
        for (( i=0; i<GPUS_PER_TASK; i++ )); do
            local idx="${indices[$((s+i))]}"
            local util="${_GPU_UTIL[$idx]}"
            local free="${_GPU_FREE[$idx]}"
            if (( PER_TASK_VRAM > 0 )); then
                local usable=$(( free * 85 / 100 ))
                (( usable < PER_TASK_VRAM )) && ok=0 && break
            fi
            if (( pass == 1 )); then
                (( util >= UTIL_THRESHOLD )) && ok=0 && break
            fi
        done
        if (( ok )); then
            _GROUP_START_IDX="${indices[$s]}"
            return 0
        fi
    done
    return 1
}

scan_and_dispatch() {
    _queue_empty && return

    # snapshot current GPU state into associative arrays
    declare -A _GPU_UTIL _GPU_FREE
    local -a _sorted_indices=()
    while IFS=' ' read -r idx util free_mib; do
        _GPU_UTIL[$idx]=$util
        _GPU_FREE[$idx]=$free_mib
        _sorted_indices+=("$idx")
    done < <(nvidia-smi --query-gpu=index,utilization.gpu,memory.free \
                        --format=csv,noheader,nounits 2>/dev/null \
             | awk -F',' '{printf "%s %s %s\n",$1,$2,$3}' \
             | sort -k2 -n)

    # pass 1: util + VRAM
    local _GROUP_START_IDX=""
    while ! _queue_empty; do
        if _find_group 1 "${_sorted_indices[@]}"; then
            _launch "$_GROUP_START_IDX" "$(_queue_pop)"
        else
            break
        fi
    done

    # pass 2: VRAM only — fill to MIN_CONCURRENCY
    if (( _RUNNING < MIN_CONCURRENCY )) && ! _queue_empty; then
        while ! _queue_empty && (( _RUNNING < MIN_CONCURRENCY )); do
            if _find_group 2 "${_sorted_indices[@]}"; then
                _launch "$_GROUP_START_IDX" "$(_queue_pop)"
            else
                break
            fi
        done
    fi
}

# ── main ─────────────────────────────────────────────────────────────────────

if ! command -v nvidia-smi &>/dev/null; then
    echo "ERROR: nvidia-smi not found. Check GPU drivers." >&2
    exit 1
fi

[[ -n "$ENV_ACTIVATE" ]] && eval "$ENV_ACTIVATE"

echo "Starting dispatcher | tasks: ${#_QUEUE[@]} | gpus_per_task: $GPUS_PER_TASK | min_concurrency: $MIN_CONCURRENCY"
echo "Logs → $LOG_DIR"

scan_and_dispatch

while (( _RUNNING > 0 )) || ! _queue_empty; do
    if wait -n 2>/dev/null; then
        (( _RUNNING-- )) || true
    else
        wait
        _RUNNING=0
    fi
    scan_and_dispatch
done

echo "All tasks done. Logs: $LOG_DIR"
